server:
  port: 8089

spring:
  profiles:
    active: dev
---    
spring:
  mvc:
   view:
    prefix: /WEB-INF/views/
    suffix: .jsp        
  
logging:
  level:
    org.springframework.web: debug
    antigravity.controller: debug
    antigravity.service: debug
    antigravity.repository: debug
    antigravity.entity: debug
  
